apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: selfish-condor-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: selfish-condor-go 
  name: selfish-condor-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: selfish-condor-go 
